language: rust
cache:
  - pip
  - cargo
before_script:
  # Install libbap
  - wget https://github.com/maurer/bap-rust/releases/download/v0.1-alpha/libbap_1.1.0.tar.xz
  - tar xf libbap_1.1.0.tar.xz
  - mkdir -p $HOME/.local/bap
  - mkdir -p $HOME/.local/lib
  - mkdir -p $HOME/.local/include
  - cp -r bap/plugins $HOME/.local/bap
  - cp -r bap/libbap* $HOME/.local/lib/libbap.so
  - cp -r bap/bap.h $HOME/.local/include
  # Fetch travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

sudo: false
addons:
  postgresql: 9.5
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - clang-3.9
    - libclang-3.9-dev
    - curl
    - libcurl4-openssl-dev
    - libgmp-dev
    - libssl-dev
    - libzip-dev
    - llvm-3.9-dev
    - m4
    - time

rust:
  - nightly
  - beta
  - stable

script:
  - travis-cargo build -- --all-features
  - travis-cargo test -- --all-features
  - travis-cargo bench -- --all-features
  - travis-cargo --only stable doc -- --all-features

after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - BAP_LIB_DIR=$HOME/.local/lib
    - BAP_PLUGIN_PATH=$HOME/.local/bap/plugins
    - BAP_INCLUDE_DIR=$HOME/.local/include
    - C_INCLUDE_PATH=$HOME/.local/include
    - LIBCLANG_PATH=/usr/lib/clang/3.9/lib/linux/
    - LLVM_CONFIG_PATH=/usr/bin/llvm-config-3.9
    - secure: "NEgBVKwxpPPtpIbSVTtSB7fUtVFrjE6FleFv3jwPRVZSYiINl7N9r5EmgB1Rb60KCLndD7kbguOjoABvVhpwR5zbS8GybgMa/iWrdr36sRGooFzEO+ItH2z659lUh6af8YF8C2f0DsdpOG8GV4mO0pmeA3bGOHyLAboNiB6RQQphogcBMolJ0P+y9WPBIvyoyTKK2H4H4/tpGOuZ82ijc2Eq0FIgQBWdNsYdPbUUvuMnmt7SY3rRvfVtibbl1NvywMttjQri/g2UKh0H+foDGVWJP99lYIcsWp/IiwzmRfCknOLIYrFLn/u3qBybN6NiJgatQbDflxhgxgTv5QkeIXvx2/wsHqP2HZZAxaIKKYwQ7QlEZiEeYxXa+dNttVTOuheU7ENmPocU0+HMZgphdsh36qvphSHKbAaJZEF5GopQ6zbLa0ZVjvSUR+LN8zoH6JZPA4nS4NI/gzvM1g0VdOuBZU64PRmHHCeUK6RCuBQP01XBbfgCFcWGgSl/BiIPwN7b7q/GtzHhfPQVqL6egY1JG3+j+xZkJAU/aRh6RaX2euqT6NHUaGQjBUTmf92LuDHsq8AfyWSZI8eXBr1RoYwLeqedn3ljMoEmbmAOi5K054zHlPSLikOC5/1oWsojHJt4nYoZyjqOfOxdweVRxoreqtVKJP1B7MhSvbDSHfA="
