language: rust
cache:
  directories:
    - $HOME/.opam
    - $HOME/.cache/pip
before_cache:
  - rm -rf $HOME/.opam/log
before_script:
  # Install libbap
  - opam init -y
  - eval `opam config env`
  - travis_wait opam pin add bap git://github.com/BinaryAnalysisPlatform/bap#v1.1.0
  - cd bap-bindings
  - opam install ctypes ctypes-foreign -y
  - autoconf
  - ./configure --prefix $HOME/.local
  - make
  - mkdir -p $HOME/.local/lib
  - mkdir -p $HOME/.local/include
  - make install
  - cd ..
  # Fetch travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

sudo: false
addons:
  postgresql: 9.3
  apt:
    sources:
    - avsm
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - camlp4
    - camlp4-extra
    - clang-3.9
    - libclang-3.9-dev
    - curl
    - libcurl4-gnutls-dev
    - libgmp-dev
    - libssl-dev
    - libzip-dev
    - llvm-3.9-dev
    - llvm-3.4-dev
    - m4
    - ocaml
    - ocaml-base
    - ocaml-base-nox
    - ocaml-compiler-libs
    - ocaml-native-compilers
    - ocaml-nox
    - time
    - opam
    - aspcud
    - dejagnu

rust:
  - nightly
  - beta
  - stable

script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo bench
  - travis-cargo --only stable doc

after_success:
  - travis-cargo coveralls --no-sudo --verify
  - travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - BAP_LIB_DIR=$HOME/.local/lib
    - BAP_INCLUDE_DIR=$HOME/.local/include
    - C_INCLUDE_PATH=$HOME/.local/include
    - LIBCLANG_PATH=/usr/lib/clang/3.9/lib/linux/
    - LLVM_CONFIG_PATH=/usr/bin/llvm-config-3.9
    - secure: "NEgBVKwxpPPtpIbSVTtSB7fUtVFrjE6FleFv3jwPRVZSYiINl7N9r5EmgB1Rb60KCLndD7kbguOjoABvVhpwR5zbS8GybgMa/iWrdr36sRGooFzEO+ItH2z659lUh6af8YF8C2f0DsdpOG8GV4mO0pmeA3bGOHyLAboNiB6RQQphogcBMolJ0P+y9WPBIvyoyTKK2H4H4/tpGOuZ82ijc2Eq0FIgQBWdNsYdPbUUvuMnmt7SY3rRvfVtibbl1NvywMttjQri/g2UKh0H+foDGVWJP99lYIcsWp/IiwzmRfCknOLIYrFLn/u3qBybN6NiJgatQbDflxhgxgTv5QkeIXvx2/wsHqP2HZZAxaIKKYwQ7QlEZiEeYxXa+dNttVTOuheU7ENmPocU0+HMZgphdsh36qvphSHKbAaJZEF5GopQ6zbLa0ZVjvSUR+LN8zoH6JZPA4nS4NI/gzvM1g0VdOuBZU64PRmHHCeUK6RCuBQP01XBbfgCFcWGgSl/BiIPwN7b7q/GtzHhfPQVqL6egY1JG3+j+xZkJAU/aRh6RaX2euqT6NHUaGQjBUTmf92LuDHsq8AfyWSZI8eXBr1RoYwLeqedn3ljMoEmbmAOi5K054zHlPSLikOC5/1oWsojHJt4nYoZyjqOfOxdweVRxoreqtVKJP1B7MhSvbDSHfA="
