language: rust
cache:
  - pip
  - cargo
before_script:
  # Install libbap
  - export BAP_VERSION=1.3.0
  - wget https://github.com/BinaryAnalysisPlatform/bap/releases/download/v$BAP_VERSION/bap-$BAP_VERSION.tgz
  - wget https://github.com/BinaryAnalysisPlatform/bap/releases/download/v$BAP_VERSION/libbap-$BAP_VERSION.tgz
  - wget https://github.com/BinaryAnalysisPlatform/bap/releases/download/v$BAP_VERSION/libbap-dev-$BAP_VERSION.tgz
  - tar xf bap-$BAP_VERSION.tgz
  - tar xf libbap-$BAP_VERSION.tgz
  - tar xf libbap-dev-$BAP_VERSION.tgz
  - mkdir -p $HOME/.local/bap
  - mkdir -p $HOME/.local/lib
  - mkdir -p $HOME/.local/include
  - cp -r usr/local/lib/bap/ $HOME/.local/bap/plugins
  - cp -r usr/local/lib/libbap.so.* $HOME/.local/lib/libbap.so
  - cp -r usr/local/include/bap.h $HOME/.local/include
  # Fetch travis-cargo
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - clang-3.9
    - libclang-3.9-dev
    - curl
    - libcurl4-openssl-dev
    - libgmp-dev
    - libssl-dev
    - libzip-dev
    - llvm-3.9-dev
    - m4
    - time

rust:
  - nightly
  - beta
  - stable

script:
  - travis-cargo build -- --all-features
  - travis-cargo test -- --all-features
  - travis-cargo bench -- --all-features
  - travis-cargo --only stable doc -- --all-features

after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - BAP_LIB_DIR=$HOME/.local/lib
    - BAP_PLUGIN_PATH=$HOME/.local/bap/plugins
    - BAP_INCLUDE_DIR=$HOME/.local/include
    - LD_LIBRARY_PATH=$HOME/.local/lib
    - C_INCLUDE_PATH=$HOME/.local/include
    - LIBCLANG_PATH=/usr/lib/llvm-3.9/lib
    - LLVM_CONFIG_PATH=/usr/bin/llvm-config-3.9
    - secure: "NEgBVKwxpPPtpIbSVTtSB7fUtVFrjE6FleFv3jwPRVZSYiINl7N9r5EmgB1Rb60KCLndD7kbguOjoABvVhpwR5zbS8GybgMa/iWrdr36sRGooFzEO+ItH2z659lUh6af8YF8C2f0DsdpOG8GV4mO0pmeA3bGOHyLAboNiB6RQQphogcBMolJ0P+y9WPBIvyoyTKK2H4H4/tpGOuZ82ijc2Eq0FIgQBWdNsYdPbUUvuMnmt7SY3rRvfVtibbl1NvywMttjQri/g2UKh0H+foDGVWJP99lYIcsWp/IiwzmRfCknOLIYrFLn/u3qBybN6NiJgatQbDflxhgxgTv5QkeIXvx2/wsHqP2HZZAxaIKKYwQ7QlEZiEeYxXa+dNttVTOuheU7ENmPocU0+HMZgphdsh36qvphSHKbAaJZEF5GopQ6zbLa0ZVjvSUR+LN8zoH6JZPA4nS4NI/gzvM1g0VdOuBZU64PRmHHCeUK6RCuBQP01XBbfgCFcWGgSl/BiIPwN7b7q/GtzHhfPQVqL6egY1JG3+j+xZkJAU/aRh6RaX2euqT6NHUaGQjBUTmf92LuDHsq8AfyWSZI8eXBr1RoYwLeqedn3ljMoEmbmAOi5K054zHlPSLikOC5/1oWsojHJt4nYoZyjqOfOxdweVRxoreqtVKJP1B7MhSvbDSHfA="
